### ISSUE TITLE
可以免登录

### ISSUE THREAD

**Issue by yfdyh000** [TechDecryptor/pot-app-recognize-plugin-baimiao#1]
`login()` `let res1 = await fetch(url + "/api/user/login", {` to `let res1 = await fetch(url + "/api/user/login/anonymous", {`
并去除`body`。

所以，要求登录账号是有什么考量吗？

**Comment by TechDecryptor** [comment]
白描是按 IP 限制用量的，不登录或者登录没有会员的账号，每天只能用五次，实际上这个插件只适合白描会员使用。

**Comment by yfdyh000** [comment]
原来如此，我是轻度用户，每次只识别了几张，所以不曾注意。
https://web.baimiaoapp.com/ 中一次上传六七张图片并识别，好像没有立即触发5张的限制，再次识别才提示。
