### ISSUE TITLE
不能使用邮箱登录

### ISSUE THREAD

**Issue by sglzp** [TechDecryptor/pot-app-recognize-plugin-baimiao#2]
登录body的type值固定为mobile，导致不能使用邮箱登录，应该根据username判断为mobile或email

**Comment by TechDecryptor** [comment]
感谢反馈，已经修复 https://github.com/TechDecryptor/pot-app-recognize-plugin-baimiao/commit/27960515c61a0b3b0d14e13aa5b9c3eaa3b5b9d3
